version: "3.4"

x-common-variables:
  &env-vars
  PORT_API: 8080
  RS_ROOT_URI: mongodb://mongo1-db:27017

networks:
  api-net:

services:
  mongo1:
    container_name: mongo1-db
    image: mongo:4.4.4
    command: --replSet devSingleNodeRs
    ports:
      - "27017:27017"
    networks:
      - api-net

  rs-setup:
    container_name: rs-setup
    image: mongo:4.4.4
    command: bash -c "
      sleep 5 &&
      mongo --host mongo1-db --port 27017 --eval \"rs.initiate()\" &&
      sleep 2 &&
      mongo --host mongo1-db --port 27017 --eval \"rs.status()\" &&
      sleep infinity"
    depends_on:
      - mongo1
    networks:
      - api-net

  api:
    container_name: api
    image: pauloportfolio/api
    build:
      context: ../..
      dockerfile: ./docker/rs-singlenode/Dockerfile
      args:
        JAR_FILE: target/*.jar
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ../docker/rs-singlenode/mongo-data-db-rs:/data/db
    depends_on:
      - rs-setup
    networks:
      - api-net
    env_file:
      - dev-singlenode-replicaset-noauth.env
    environment:
      PORT_DEBUG: 5005
      <<: *env-vars
      DEBUG_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m